server:
  port: 9090
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pao?serverTimezone=GMT%2b8
      username: root
      password: ljf020821
  mvc:
    static-path-pattern: /video/**
  servlet:
    multipart:
      max-file-size: 200MB
mybatis:
  mapper-locations:
    classpath: mapper/*.xml
